### ISSUE TITLE
go get can not get the source

### ISSUE THREAD

**Issue by zlyang** [jrmsdev/go-jdb#1]
go get -v go.jrms.com.ar/jdb/storage/file

Fetching https://go.jrms.com.ar/jdb/storage/file?go-get=1
https fetch failed.
import "go.jrms.com.ar/jdb/storage/file": https fetch: Get https://go.jrms.com.ar/jdb/storage/file?go-get=1: x509: certificate is valid for amidamaru.com.ar, zenkon.amidamaru.com.ar, not go.jrms.com.ar
package go.jrms.com.ar/jdb/storage/file: unrecognized import path "go.jrms.com.ar/jdb/storage/file"

**Comment by jrmsgit** [comment]
Hi, thanks for reporting this. I think the HTTPS part is fixed now.

But I'm curious, are you using this Go code? I never really finished it nor used it for anything really. I wrote it to learn some of Go.

Cheers,


jeremías

**Comment by zlyang** [comment]
I want a key-vale database base on file,so search in github.And I used MySQL now.
tks,

yang
